from . import contract_config
from . import payroll_config
from . import tax_calculations
from . import hr_employee_details
from . import hr_payslip
from . import it_statement
from . import employee_full_final
from . import hr_attendance_shortfall
from . import res_company
#from fiscalyear import fiscalyear
